### ISSUE TITLE
utils.pm dependency

### ISSUE THREAD

**Issue by dooblem** [shinken-monitoring/pack-linux-snmp#10]
I just installed linux-snmp pack on a fresh Shinken (Ubuntu distro). I had the following problem:
```
$ /var/lib/shinken/libexec/check_snmp_load.pl -H XXXXX -C public -f -w 80 -c 90 -o 65535
Can't locate utils.pm in @INC (you may need to install the utils module) (@INC contains: /var/lib/shinken/libexec /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /var/lib/shinken/libexec/check_snmp_load.pl line 22.
BEGIN failed--compilation aborted at /var/lib/shinken/libexec/check_snmp_load.pl line 22.
```

As the nagios-plugins-common package is installed, I used the workaround:
ln -s /usr/lib/nagios/plugins/utils.pm /var/lib/shinken/libexec/utils.pm

Maybe we should ask upstream if it's possible to have the  /usr/lib/nagios/plugins added in perl path ?

See also:
http://www.shinken-monitoring.org/forum/index.php?topic=1680.0
http://nagios.proy.org/snmp_load.html

**Comment by Wicaeed** [comment]
FYI this is still an issue as of 10/23/2015

**Comment by nicodmf** [comment]
Same here 28/03/2016, and thanks for the workarrounds

**Comment by mdahiemstra** [comment]
+1

**Comment by claneys** [comment]
Dirty fix in plugins that avoid the issue. Pack version 1.6 got the fix.
